apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-management-service
  template:
    metadata:
      labels:
        app: task-management-service
    spec:
      containers:
        - image: zigakleine/task-management-service:1.0.0-SNAPSHOT-9.1
          name: task-management-service
          env:
            - name: DBURL
              value: jdbc:postgresql://dumbo.db.elephantsql.com:5432/tzhaeear
            - name: DBUSERNAME
              value: tzhaeear
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pass-task-management
                  key: DBPASSWORD
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
            #livenessProbe:
            # httpGet:
            #  path: /v1/files/checks/health
            # port: server
            #initialDelaySeconds: 60
            #periodSeconds: 3
            #readinessProbe:
            # httpGet:
            #  path: /v1/files/checks/health
            # port: server
            #initialDelaySeconds: 60
            #periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: task-management-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: task-management-service